name: main

on:
  push:
    branches:
      - main
#   schedule:
#     - cron: 0 22 * * 0

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - run: npm i

      - run: node main.mjs
        env:
          NX: ${{ secrets.NX }}
          NY: ${{ secrets.NY }}
          REGID: ${{ secrets.REGID }}
          SCHOOL_NAME: ${{ secrets.SCHOOL_NAME }}
          SERVICEKEY: ${{ secrets.SERVICEKEY }}

      - name: Compile Typst File
        uses: ammar-ahmed22/compile-typst-action@v1
        with:
          source_paths: 'main.typ'
          output_paths: 'main.pdf'
          fonts_path: 'fonts'

      - run: node sendPng.mjs
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
