name: main

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 22 * * 0

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm i

      - run: node main.mjs
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          NX: ${{ secrets.NX }}
          NY: ${{ secrets.NY }}
          REGID: ${{ secrets.REGID }}
          SCHOOL_NAME: ${{ secrets.SCHOOL_NAME }}
          SERVICEKEY: ${{ secrets.SERVICEKEY }}

      - name: Compile Typst File
        uses: ammar-ahmed22/compile-typst-action@v1
        with:
          source_paths: 'main.typ'
          output_paths: 'main.pdf'
          fonts_path: 'fonts'

      - run: apt-get update && apt-get install imagemagick

      - run: node sendPng.mjs
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          NX: ${{ secrets.NX }}
          NY: ${{ secrets.NY }}
          REGID: ${{ secrets.REGID }}
          SCHOOL_NAME: ${{ secrets.SCHOOL_NAME }}
          SERVICEKEY: ${{ secrets.SERVICEKEY }}
